# agents/in-progress/equipment_gen.py
#
# Stage: Generate a self-contained Roll20 mod (API) script from the curated
# weapon & armor catalog (data/input/equipment.json). The script lets players
# equip homebrew DCC gear onto the selected character with one command:
#   !equip <item>      add a weapon row (damage + type) or set armor-vector AC
#   !unequip <item>    remove the matching weapon row / clear armor vectors
#   !armor [name]      whisper an armor's P/S/B AC and penalties
#   !weapon <name>     whisper a weapon's damage, type, and homebrew property
#   !crit <weapon>     whisper the weapon's crit effect
#   !equip-list        whisper the catalog index
#   !equip-diag [name] dump a sheet's attributes (by character name, or the
#                      selected token) to find real field names / verify which
#                      fields the API can set
#
# This mirrors encounter_gen.py: read staged data -> validate -> emit a ready
# .js. No Claude call — the catalog is static reference data.
#
# Usage: python run.py equipment --build

import json
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent.parent  # agents/in-progress -> project root
CATALOG_PATH = _ROOT / 'data' / 'input' / 'equipment.json'
READY_DIR = _ROOT / 'data' / 'output' / 'ready'
PENDING_DIR = _ROOT / 'data' / 'output' / 'pending'

DAMAGE_TYPES = {'piercing', 'slashing', 'bludgeoning', 'special'}
RANGES = {'melee', 'missile'}


def load_catalog(path=CATALOG_PATH):
    """Read and parse the equipment catalog JSON."""
    return json.loads(Path(path).read_text(encoding='utf-8'))


def validate_catalog(catalog):
    """Validate the catalog dict. Returns a list of error strings (empty == ok)."""
    errors = []
    weapons = catalog.get('weapons', [])
    armor = catalog.get('armor', [])

    if not isinstance(weapons, list):
        errors.append("'weapons' must be a list")
        weapons = []
    if not isinstance(armor, list):
        errors.append("'armor' must be a list")
        armor = []

    for i, w in enumerate(weapons):
        label = w.get('name', f'#{i}')
        for field in ('name', 'damage', 'damage_type', 'range'):
            if field not in w:
                errors.append(f"weapon {label}: missing '{field}'")
        if w.get('damage_type') not in DAMAGE_TYPES and 'damage_type' in w:
            errors.append(f"weapon {label}: damage_type {w['damage_type']!r} not in {sorted(DAMAGE_TYPES)}")
        if w.get('range') not in RANGES and 'range' in w:
            errors.append(f"weapon {label}: range {w['range']!r} not in {sorted(RANGES)}")

    for i, a in enumerate(armor):
        label = a.get('name', f'#{i}')
        if 'name' not in a:
            errors.append(f"armor {label}: missing 'name'")
        if a.get('is_shield'):
            if not isinstance(a.get('ac_bonus_all'), int):
                errors.append(f"armor {label}: shield must have integer 'ac_bonus_all'")
        else:
            for field in ('base_ac', 'ac_slashing', 'ac_piercing', 'ac_bludgeoning'):
                if not isinstance(a.get(field), int):
                    errors.append(f"armor {label}: '{field}' must be an integer")

    names = [item.get('name', '') for item in weapons + armor]
    seen = set()
    for n in names:
        key = n.strip().lower()
        if key in seen:
            errors.append(f"duplicate item name: {n!r}")
        seen.add(key)

    return errors


def weapon_attrs(weapon):
    """Repeating-section field suffixes -> values for an equipped weapon.

    The generated script writes these as repeating_weapons_<rowid>_<suffix>.
    Derived attack bonus is intentionally left to the sheet (it depends on the
    character's STR/AGL/level).
    """
    return {
        'name': weapon['name'],
        'damage': weapon['damage'],
        'damage_base': weapon['damage'],
        'type': weapon['range'],
    }


def armor_vectors(armor):
    """Return (piercing, slashing, bludgeoning) AC for a (non-shield) armor."""
    return (armor['ac_piercing'], armor['ac_slashing'], armor['ac_bludgeoning'])


def armor_vector_string(p, s, b):
    """Format the project-standard armor-vector text, e.g. 'AC: P12/S12/B12'."""
    return f"AC: P{p}/S{s}/B{b}"


def apply_shield(vectors, bonus):
    """Add a shield's flat bonus to each of (p, s, b)."""
    p, s, b = vectors
    return (p + bonus, s + bonus, b + bonus)


# --- Roll20 mod script body (logic is written once here in JS) ---------------
# The catalog is injected ahead of this block as `var CATALOG = {...};`.
_SCRIPT_BODY = r"""
// ---------------------------------------------------------------------------
// Thracia Equipment — Roll20 mod (API) script. Auto-generated by equipment_gen.
// Paste into Campaign Settings -> Mod (API) Scripts. Do not edit by hand;
// edit data/input/equipment.json and re-run: python run.py equipment --build
// ---------------------------------------------------------------------------
var ThraciaEquipment = (function () {
    'use strict';

    var VECTOR_RE = /AC:\s*P(-?\d+)\/S(-?\d+)\/B(-?\d+)/i;

    function norm(s) { return String(s || '').trim().toLowerCase(); }

    function findItem(name) {
        var key = norm(name);
        var all = (CATALOG.weapons || []).concat(CATALOG.armor || []);
        for (var i = 0; i < all.length; i++) {
            if (norm(all[i].name) === key) return all[i];
        }
        return null;
    }

    function isWeapon(item) { return item && item.range !== undefined && item.damage !== undefined; }

    function whisper(to, text) {
        // msg.who comes through as e.g. "Christian L. (GM)"; the " (GM)" suffix
        // breaks /w target lookup, so strip it before whispering.
        to = String(to || 'gm').replace(/\s*\(GM\)$/, '');
        sendChat('Equipment', '/w "' + to + '" ' + text, null, { noarchive: true });
    }

    function charFromMsg(msg) {
        if (!msg.selected || !msg.selected.length) return null;
        var tok = getObj('graphic', msg.selected[0]._id);
        if (!tok) return null;
        var cid = tok.get('represents');
        return cid || null;
    }

    function charByName(name) {
        var key = norm(name);
        var chars = findObjs({ type: 'character' });
        for (var i = 0; i < chars.length; i++) {
            if (norm(chars[i].get('name')) === key) return chars[i].id;
        }
        return null;
    }

    // Resolve a character from an explicit name (if given) or the selected token.
    function resolveChar(msg, name) {
        return name ? charByName(name) : charFromMsg(msg);
    }

    function getAttrObj(cid, name) {
        var objs = findObjs({ type: 'attribute', characterid: cid, name: name });
        return objs.length ? objs[0] : null;
    }

    function setAttr(cid, name, value) {
        var a = getAttrObj(cid, name);
        if (a) { a.set('current', value); return a; }
        return createObj('attribute', { characterid: cid, name: name, current: value });
    }

    function getAttrVal(cid, name, dflt) {
        var a = getAttrObj(cid, name);
        return a ? a.get('current') : dflt;
    }

    function writeVectors(cid, p, s, b) {
        var desc = String(getAttrVal(cid, 'description', '') || '');
        var vec = 'AC: P' + p + '/S' + s + '/B' + b;
        if (VECTOR_RE.test(desc)) {
            desc = desc.replace(VECTOR_RE, vec);
        } else {
            desc = (desc ? desc + ' ' : '') + vec + '.';
        }
        setAttr(cid, 'description', desc);
    }

    function readVectors(cid) {
        var desc = String(getAttrVal(cid, 'description', '') || '');
        var m = VECTOR_RE.exec(desc);
        if (!m) return null;
        return { p: parseInt(m[1], 10), s: parseInt(m[2], 10), b: parseInt(m[3], 10) };
    }

    function equip(msg, name) {
        var item = findItem(name);
        if (!item) { whisper(msg.who, 'No item named "' + name + '". Try !equip-list.'); return; }
        var cid = charFromMsg(msg);
        if (!cid) { whisper(msg.who, 'Select a token that represents a character first.'); return; }
        var cname = (getObj('character', cid) || { get: function () { return 'character'; } }).get('name');

        if (isWeapon(item)) {
            var row = generateRowID();
            setAttr(cid, 'repeating_weapons_' + row + '_name', item.name);
            setAttr(cid, 'repeating_weapons_' + row + '_damage', item.damage);
            setAttr(cid, 'repeating_weapons_' + row + '_damage_base', item.damage);
            setAttr(cid, 'repeating_weapons_' + row + '_type', item.range);
            var erow = generateRowID();
            setAttr(cid, 'repeating_equipment_' + erow + '_name', item.name);
            setAttr(cid, 'repeating_equipment_' + erow + '_active', '1');
            whisper(msg.who, '<b>' + cname + '</b> equipped <b>' + item.name + '</b> (' +
                item.damage + ' ' + item.damage_type + ', ' + item.range + ').');
            return;
        }

        // Armor
        if (item.is_shield) {
            var cur = readVectors(cid);
            if (!cur) {
                whisper(msg.who, 'Equip body armor before a shield (no AC vectors set yet).');
                return;
            }
            var bonus = item.ac_bonus_all || 0;
            writeVectors(cid, cur.p + bonus, cur.s + bonus, cur.b + bonus);
            var ac = parseInt(getAttrVal(cid, 'ac', cur.b), 10) || cur.b;
            setAttr(cid, 'ac', ac + bonus);
            whisper(msg.who, '<b>' + cname + '</b> raised <b>' + item.name + '</b> (+' + bonus + ' all vectors).');
            return;
        }
        writeVectors(cid, item.ac_piercing, item.ac_slashing, item.ac_bludgeoning);
        setAttr(cid, 'ac', item.base_ac);
        whisper(msg.who, '<b>' + cname + '</b> donned <b>' + item.name + '</b> (AC: P' +
            item.ac_piercing + '/S' + item.ac_slashing + '/B' + item.ac_bludgeoning + ').');
    }

    function unequip(msg, name) {
        var cid = charFromMsg(msg);
        if (!cid) { whisper(msg.who, 'Select a token that represents a character first.'); return; }
        var key = norm(name);
        var attrs = findObjs({ type: 'attribute', characterid: cid });
        var removedRows = {};
        // find rowids whose _name matches in repeating_weapons / repeating_equipment
        attrs.forEach(function (a) {
            var nm = a.get('name');
            var m = nm.match(/^(repeating_(?:weapons|equipment))_([^_]+)_name$/);
            if (m && norm(a.get('current')) === key) {
                removedRows[m[1] + '_' + m[2]] = true;
            }
        });
        var count = 0;
        attrs.forEach(function (a) {
            var nm = a.get('name');
            for (var prefix in removedRows) {
                if (nm.indexOf(prefix + '_') === 0) { a.remove(); count++; break; }
            }
        });
        whisper(msg.who, count ? 'Unequipped "' + name + '".' : 'No equipped item named "' + name + '".');
    }

    function lookupArmor(msg, name) {
        if (!name) {
            var list = (CATALOG.armor || []).map(function (a) { return a.name; }).join(', ');
            whisper(msg.who, '<b>Armor:</b> ' + list);
            return;
        }
        var item = findItem(name);
        if (!item || item.is_shield === undefined) {
            whisper(msg.who, 'No armor named "' + name + '".');
            return;
        }
        if (item.is_shield) {
            whisper(msg.who, '<b>' + item.name + '</b>: +' + item.ac_bonus_all + ' AC all vectors, check ' +
                item.check_penalty + ', fumble ' + item.fumble_die + (item.notes ? '. ' + item.notes : ''));
        } else {
            whisper(msg.who, '<b>' + item.name + '</b>: AC P' + item.ac_piercing + '/S' + item.ac_slashing +
                '/B' + item.ac_bludgeoning + ' (base ' + item.base_ac + '), check ' + item.check_penalty +
                ', speed ' + item.speed_penalty + "', fumble " + item.fumble_die);
        }
    }

    function lookupWeapon(msg, name) {
        var item = findItem(name);
        if (!item || !isWeapon(item)) { whisper(msg.who, 'No weapon named "' + name + '".'); return; }
        var extra = item.crit_note ? ' Crit: ' + item.crit_note + '.' : '';
        if (item.notes) extra += ' ' + item.notes + '.';
        whisper(msg.who, '<b>' + item.name + '</b>: ' + item.damage + ' ' + item.damage_type +
            ', ' + item.range + ', size ' + (item.size || '?') + '.' + extra);
    }

    function lookupCrit(msg, name) {
        var item = findItem(name);
        if (!item || !isWeapon(item)) { whisper(msg.who, 'No weapon named "' + name + '".'); return; }
        whisper(msg.who, '<b>' + item.name + '</b> crit: ' + (item.crit_note || 'standard DCC crit') +
            '. (Bronze: 50% sunder on crit fail.)');
    }

    function listAll(msg) {
        var w = (CATALOG.weapons || []).map(function (i) { return i.name; }).join(', ');
        var a = (CATALOG.armor || []).map(function (i) { return i.name; }).join(', ');
        whisper(msg.who, '<b>Weapons:</b> ' + w + '<br><b>Armor:</b> ' + a);
    }

    // Diagnostic: discover this sheet's real attribute names and which fields
    // the API can actually set (vs. fields the sheet recomputes/clobbers).
    //   !equip-diag [name]        dump all attrs to API console + whisper subset
    //   !equip-diag probe [name]  write sentinel values (99 / 1d99) to candidates
    // [name] targets a character by name; omit it to use the selected token.
    function diag(msg, arg) {
        var probe = false;
        var name = String(arg || '').trim();
        var parts = name.split(/\s+/).filter(function (p) { return p.length; });
        if (parts.length && parts[0].toLowerCase() === 'probe') {
            probe = true;
            name = parts.slice(1).join(' ');
        }
        var cid = resolveChar(msg, name);
        if (!cid) {
            whisper(msg.who, name ? ('No character named "' + name + '".')
                : 'Select a token that represents a character, or run: !equip-diag &lt;character name&gt;');
            return;
        }
        var attrs = findObjs({ type: 'attribute', characterid: cid });

        if (probe) {
            var sentinels = {
                armor_class: '99', ac: '99', speed: '99', speed_mod: '99',
                initiative: '1d99', initiative_overwritten: '1d99', initiative_mod: '99'
            };
            var wrote = [];
            for (var k in sentinels) { setAttr(cid, k, sentinels[k]); wrote.push(k); }
            whisper(msg.who, 'Probe wrote sentinels (99 / 1d99) to: ' + wrote.join(', ') +
                '.<br>Open the sheet and note which sentinels actually show &mdash; those fields are ' +
                'API-writable. Reset/re-open the sheet afterward. (Use a disposable test PC.)');
            return;
        }

        var all = attrs.map(function (a) { return a.get('name') + ' = ' + a.get('current'); }).sort();
        log('=== equip-diag: ' + all.length + ' attributes on character ' + cid + ' ===');
        all.forEach(function (line) { log('  ' + line); });
        var rx = /ac|armor|agi|init|speed|fumble|check|encumb|load/i;
        var relevant = attrs.filter(function (a) { return rx.test(a.get('name')); })
            .map(function (a) { return a.get('name') + ' = ' + a.get('current'); }).sort();
        whisper(msg.who, '<b>' + all.length + ' attributes</b> dumped to the API console (copy them to me).' +
            '<br><b>Combat-relevant:</b><br>' + (relevant.join('<br>') || '(none matched)'));
    }

    function handle(msg) {
        if (msg.type !== 'api') return;
        var parts = msg.content.replace(/^!/, '').split(/\s+/);
        var cmd = parts.shift().toLowerCase();
        var arg = parts.join(' ').trim();
        switch (cmd) {
            case 'equip': equip(msg, arg); break;
            case 'unequip': unequip(msg, arg); break;
            case 'armor': lookupArmor(msg, arg); break;
            case 'weapon': lookupWeapon(msg, arg); break;
            case 'crit': lookupCrit(msg, arg); break;
            case 'equip-list': listAll(msg); break;
            case 'equip-diag': diag(msg, arg); break;
        }
    }

    on('chat:message', handle);
    log('Thracia Equipment ready: ' + (CATALOG.weapons || []).length + ' weapons, ' +
        (CATALOG.armor || []).length + ' armor.');

    return { handle: handle, findItem: findItem };
})();
"""


def build_script(catalog):
    """Render the self-contained Roll20 mod script with the catalog embedded."""
    header = (
        "// Thracia Equipment catalog — auto-generated. Do not edit by hand.\n"
        "// Source: data/input/equipment.json\n\n"
    )
    catalog_js = "var CATALOG = " + json.dumps(catalog, indent=2, ensure_ascii=False) + ";\n"
    return header + catalog_js + _SCRIPT_BODY


# --- Player-facing handout (browsable HTML gear list) -----------------------

def _esc(value):
    """Minimal HTML escape for catalog values."""
    return (
        str(value)
        .replace('&', '&amp;')
        .replace('<', '&lt;')
        .replace('>', '&gt;')
    )


def _weapon_special(weapon):
    """Compose the player-facing 'Special' cell for a weapon."""
    bits = []
    if weapon.get('two_handed'):
        bits.append('two-handed')
    if weapon.get('reach'):
        bits.append('reach')
    if weapon.get('finesse'):
        bits.append('finesse (AGL)')
    if weapon.get('thrown'):
        bits.append(f"thrown {weapon['thrown']}")
    if weapon.get('crit_note'):
        bits.append(weapon['crit_note'])
    if weapon.get('notes'):
        bits.append(weapon['notes'])
    return _esc('; '.join(bits))


def build_weapons_table_html(weapons):
    """Render the weapons reference table as HTML."""
    head = (
        "<tr><th>Weapon</th><th>Dmg</th><th>Type</th><th>Size</th>"
        "<th>Range</th><th>Special</th><th>Cost</th></tr>"
    )
    rows = []
    for w in weapons:
        rows.append(
            "<tr>"
            f"<td><strong>{_esc(w['name'])}</strong></td>"
            f"<td>{_esc(w['damage'])}</td>"
            f"<td>{_esc(w['damage_type'])}</td>"
            f"<td>{_esc(w.get('size', '-'))}</td>"
            f"<td>{_esc(w['range'])}</td>"
            f"<td>{_weapon_special(w)}</td>"
            f"<td>{_esc(w.get('cost', '-'))}</td>"
            "</tr>"
        )
    return f"<table border='1' cellpadding='4'><thead>{head}</thead><tbody>{''.join(rows)}</tbody></table>"


def build_armor_table_html(armor):
    """Render the body-armor reference table (non-shield entries) as HTML."""
    head = (
        "<tr><th>Armor</th><th>Base</th><th>P</th><th>S</th><th>B</th>"
        "<th>Max AGL</th><th>Check</th><th>Speed</th><th>Fumble</th><th>Cost</th></tr>"
    )
    rows = []
    for a in armor:
        if a.get('is_shield'):
            continue
        agl = a.get('max_agl_mod')
        agl_str = '-' if agl is None else f"+{agl}"
        speed = a.get('speed_penalty', 0)
        speed_str = '-' if not speed else f"{speed}'"
        rows.append(
            "<tr>"
            f"<td><strong>{_esc(a['name'])}</strong></td>"
            f"<td>{a['base_ac']}</td>"
            f"<td>{a['ac_piercing']}</td>"
            f"<td>{a['ac_slashing']}</td>"
            f"<td>{a['ac_bludgeoning']}</td>"
            f"<td>{_esc(agl_str)}</td>"
            f"<td>{_esc(a.get('check_penalty', 0) or '-')}</td>"
            f"<td>{_esc(speed_str)}</td>"
            f"<td>{_esc(a.get('fumble_die', '-'))}</td>"
            f"<td>{_esc(a.get('cost', '-'))}</td>"
            "</tr>"
        )
    return f"<table border='1' cellpadding='4'><thead>{head}</thead><tbody>{''.join(rows)}</tbody></table>"


def build_shields_table_html(armor):
    """Render the shields reference table (is_shield entries) as HTML."""
    head = (
        "<tr><th>Shield</th><th>AC Bonus</th><th>Check</th>"
        "<th>Fumble</th><th>Cost</th><th>Notes</th></tr>"
    )
    rows = []
    for a in armor:
        if not a.get('is_shield'):
            continue
        rows.append(
            "<tr>"
            f"<td><strong>{_esc(a['name'])}</strong></td>"
            f"<td>+{a['ac_bonus_all']}</td>"
            f"<td>{_esc(a.get('check_penalty', 0) or '-')}</td>"
            f"<td>{_esc(a.get('fumble_die', '-'))}</td>"
            f"<td>{_esc(a.get('cost', '-'))}</td>"
            f"<td>{_esc(a.get('notes', ''))}</td>"
            "</tr>"
        )
    return f"<table border='1' cellpadding='4'><thead>{head}</thead><tbody>{''.join(rows)}</tbody></table>"


def build_handout(catalog):
    """Build a Roll20 handout dict with a browsable, player-facing gear list.

    The same shape room_gen emits, so it flows through QAChecker (`python run.py
    qa`) and any future handout importer.
    """
    weapons = catalog.get('weapons', [])
    armor = catalog.get('armor', [])
    notes = (
        "<h2>Weapons &amp; Armor</h2>"
        "<p>Armor protects differently against each damage type. AC is shown as "
        "<strong>P</strong>iercing / <strong>S</strong>lashing / "
        "<strong>B</strong>ludgeoning &mdash; choose your weapon accordingly.</p>"
        "<h3>Weapons</h3>"
        + build_weapons_table_html(weapons)
        + "<h3>Armor</h3>"
        + build_armor_table_html(armor)
        + "<h3>Shields</h3>"
        + build_shields_table_html(armor)
    )
    gmnotes = (
        "Auto-generated from data/input/equipment.json by equipment_gen. "
        "Edit the catalog and re-run `python run.py equipment --handout` to refresh. "
        "Kept in sync with the !equip mod script."
    )
    return {
        'type': 'handout',
        'name': 'Equipment - Weapons & Armor',
        'notes': notes,
        'gmnotes': gmnotes,
        'folder': 'Reference',
    }


def run_handout():
    """Build the player-facing handout JSON and write it to data/output/pending/."""
    catalog = load_catalog(CATALOG_PATH)
    errors = validate_catalog(catalog)
    if errors:
        raise ValueError(f"[EquipmentGen] Catalog validation errors: {errors}")

    handout = build_handout(catalog)
    Path(PENDING_DIR).mkdir(parents=True, exist_ok=True)
    out_path = Path(PENDING_DIR) / 'equipment_handout.json'
    out_path.write_text(json.dumps(handout, indent=2, ensure_ascii=False), encoding='utf-8')
    print(f"EquipmentGen: handout '{handout['name']}' -> {out_path} (run `python run.py qa` to validate)")


def run():
    """Load + validate the catalog, then write equipment.js to data/output/ready/."""
    catalog = load_catalog(CATALOG_PATH)
    errors = validate_catalog(catalog)
    if errors:
        raise ValueError(f"[EquipmentGen] Catalog validation errors: {errors}")

    js = build_script(catalog)
    Path(READY_DIR).mkdir(parents=True, exist_ok=True)
    out_path = Path(READY_DIR) / 'equipment.js'
    out_path.write_text(js, encoding='utf-8')
    n_w = len(catalog.get('weapons', []))
    n_a = len(catalog.get('armor', []))
    print(f"EquipmentGen: {n_w} weapons + {n_a} armor -> {out_path}")
